version: '3'

services:
  db:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./tmp/postgres:/var/lib/postgresql/data
  web:
    build:
        context: ./web
        args:
            requirements: dev
    command: "adev runserver app"
    entrypoint: ["./wait-for-db.sh"]
    environment:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASS=postgres
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
